[package]
name = "server"
version = "0.1.0"
edition = "2024"
default-run = "server"
build = "build.rs"

[dependencies]
axum = { version = "0.8.4", features = ["ws"] }
tokio = { version = "1", features = ["process", "rt-multi-thread", "sync"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
axum-extra = { version = "0.10.1", features = ["typed-header"] }
headers = "0.4.1"
futures-util = "0.3.31"
tracing = "0.1.41"
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
