[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
ratzilla = "0.1"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["WebSocket", "MessageEvent"] }
